name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up environment
      - name: Set up Bash
        run: sudo apt-get install -y bash

      # Step 2: Set up Bash (already installed in the environment)
      - name: Run Bash Script to Add Hashes
        run: |
          # Write the Bash script directly
          cat << 'EOF' > add_hashes.sh
          #!/bin/bash

          CSS_DIR="./src/assets/css"
          JS_DIR="./src/assets/js"
          HTML_FILE="./src/index.html"

          # Process CSS and JS files
          for DIR in "$CSS_DIR" "$JS_DIR"; do
            if [ -d "$DIR" ]; then
              for file in "$DIR"/*.{css,js}; do
                # Ensure the file exists and has the correct extension
                if [ -f "$file" ]; then
                  # Generate a hash and rename the file
                  HASH=$(md5sum "$file" | cut -c1-8)
                  BASENAME=$(basename "$file")
                  EXT="${BASENAME##*.}"
                  NAME="${BASENAME%.*}"
                  NEW_NAME="${NAME}.${HASH}.${EXT}"

                  # Rename the file
                  mv "$file" "$DIR/$NEW_NAME"

                  # Update references in the HTML file
                  sed -i "s|$NAME.$EXT|$NEW_NAME|g" "$HTML_FILE"
                fi
              done
            fi
          done
          EOF

          # Make the script executable and run it
          chmod +x add_hashes.sh
          ./add_hashes.sh

      # Step 3: Deploy the updated files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          publish_branch: gh-pages
